// <auto-generated />
using System;
using ClairEtNet.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClairEtNet.DataContext.Migrations
{
    [DbContext(typeof(CnErpContext))]
    partial class CnErpContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClairEtNet.Model.Affectation", b =>
                {
                    b.Property<int>("Id_affectation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_affectation"));

                    b.Property<DateTime>("Date_debut_affectation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date_fin_affectation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Fonction_affectation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id_chantier")
                        .HasColumnType("int");

                    b.Property<int>("Id_employer")
                        .HasColumnType("int");

                    b.HasKey("Id_affectation");

                    b.HasIndex("Id_chantier");

                    b.HasIndex("Id_employer");

                    b.ToTable("Affectations");
                });

            modelBuilder.Entity("ClairEtNet.Model.Categorie", b =>
                {
                    b.Property<int>("Id_categorie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_categorie"));

                    b.Property<DateTime>("Created_at_categorie")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description_categorie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Libelle_categorie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at_categorie")
                        .HasColumnType("datetime2");

                    b.HasKey("Id_categorie");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id_categorie = 1,
                            Created_at_categorie = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description_categorie = "Détergents, désinfectants, nettoyants multi-surfaces et vitres",
                            Libelle_categorie = "Produits d’entretien",
                            Updated_at_categorie = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id_categorie = 2,
                            Created_at_categorie = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description_categorie = "Papier toilette, essuie-mains, savon, sacs-poubelle, recharges",
                            Libelle_categorie = "Consommables hygiène",
                            Updated_at_categorie = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id_categorie = 3,
                            Created_at_categorie = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description_categorie = "Balais, raclettes, microfibres, seaux, manches télescopiques",
                            Libelle_categorie = "Matériel manuel",
                            Updated_at_categorie = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id_categorie = 4,
                            Created_at_categorie = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description_categorie = "Autolaveuses, aspirateurs, monobrosses, balayeuses",
                            Libelle_categorie = "Équipements motorisés",
                            Updated_at_categorie = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id_categorie = 5,
                            Created_at_categorie = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description_categorie = "Gants, lunettes, masques, casques, chaussures de sécurité",
                            Libelle_categorie = "Équipements de protection (EPI)",
                            Updated_at_categorie = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id_categorie = 6,
                            Created_at_categorie = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description_categorie = "Filtres, batteries, brosses, tuyaux et autres pièces de rechange",
                            Libelle_categorie = "Pièces détachées & accessoires",
                            Updated_at_categorie = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id_categorie = 7,
                            Created_at_categorie = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description_categorie = "Panneaux sol glissant, rubalise, cônes, trousses de secours",
                            Libelle_categorie = "Signalisation & sécurité",
                            Updated_at_categorie = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id_categorie = 8,
                            Created_at_categorie = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description_categorie = "Traitements sols, anti-graffiti, détachants textiles, détartrants",
                            Libelle_categorie = "Produits spéciaux",
                            Updated_at_categorie = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id_categorie = 9,
                            Created_at_categorie = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description_categorie = "Tournevis, pinces, clés, petits outils de maintenance",
                            Libelle_categorie = "Outillage léger",
                            Updated_at_categorie = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("ClairEtNet.Model.Chantier", b =>
                {
                    b.Property<int>("Id_chantier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_chantier"));

                    b.Property<string>("Adresse_chantier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Latitude_chantier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Longitude_chantier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom_chantier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_chantier");

                    b.ToTable("Chantiers");
                });

            modelBuilder.Entity("ClairEtNet.Model.Contact", b =>
                {
                    b.Property<int>("Id_contact")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_contact"));

                    b.Property<DateTime>("Created_at_contact")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email_contact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Lu_contact")
                        .HasColumnType("bit");

                    b.Property<string>("Message_contact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reponse_contact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sujet_contact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Traite_contact")
                        .HasColumnType("bit");

                    b.HasKey("Id_contact");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("ClairEtNet.Model.Employer", b =>
                {
                    b.Property<int>("Id_employer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_employer"));

                    b.Property<DateTime>("Created_at_employer")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Id_utilisateur")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated_at_employer")
                        .HasColumnType("datetime2");

                    b.HasKey("Id_employer");

                    b.HasIndex("Id_utilisateur")
                        .IsUnique()
                        .HasFilter("[Id_utilisateur] IS NOT NULL");

                    b.ToTable("Employers");
                });

            modelBuilder.Entity("ClairEtNet.Model.Incident", b =>
                {
                    b.Property<int>("Id_incident")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_incident"));

                    b.Property<DateTime>("Created_at_incident")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description_incident")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id_chantier")
                        .HasColumnType("int");

                    b.Property<int>("Id_employer")
                        .HasColumnType("int");

                    b.Property<bool>("Priorite_incident")
                        .HasColumnType("bit");

                    b.Property<string>("Statut_incident")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titre_incident")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type_incident")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at_incident")
                        .HasColumnType("datetime2");

                    b.HasKey("Id_incident");

                    b.HasIndex("Id_chantier");

                    b.HasIndex("Id_employer");

                    b.ToTable("Incidents");
                });

            modelBuilder.Entity("ClairEtNet.Model.MouvementStock", b =>
                {
                    b.Property<int>("Id_mouvementstock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_mouvementstock"));

                    b.Property<DateTime>("Created_at_mouvementstock")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description_mouvementstock")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id_chantier")
                        .HasColumnType("int");

                    b.Property<int>("Id_stock")
                        .HasColumnType("int");

                    b.Property<int>("Id_utilisateur")
                        .HasColumnType("int");

                    b.Property<int>("Quantite_mouvementstock")
                        .HasColumnType("int");

                    b.Property<string>("Type_mouvementstock")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at_mouvementstock")
                        .HasColumnType("datetime2");

                    b.HasKey("Id_mouvementstock");

                    b.HasIndex("Id_chantier");

                    b.HasIndex("Id_stock");

                    b.HasIndex("Id_utilisateur");

                    b.ToTable("MouvementStocks");
                });

            modelBuilder.Entity("ClairEtNet.Model.Stock", b =>
                {
                    b.Property<int>("Id_stock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_stock"));

                    b.Property<DateTime>("Created_at_stock")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description_stock")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Emplacement_stock")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id_categorie")
                        .HasColumnType("int");

                    b.Property<string>("Nom_article_stock")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantite_stock")
                        .HasColumnType("int");

                    b.Property<string>("Unite_stock")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at_stock")
                        .HasColumnType("datetime2");

                    b.HasKey("Id_stock");

                    b.HasIndex("Id_categorie");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("ClairEtNet.Model.Utilisateur", b =>
                {
                    b.Property<int>("Id_utilisateur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_utilisateur"));

                    b.Property<string>("Adresse_utilisateur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_at_utilisateur")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date_naissance_utilisateur")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Donnees_supprimes_utilisateur")
                        .HasColumnType("bit");

                    b.Property<string>("Email_utilisateur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mot_de_passe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom_utilisateur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom_utilisateur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone_utilisateur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at_utilisateur")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Verified_utilisateur")
                        .HasColumnType("bit");

                    b.HasKey("Id_utilisateur");

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("ClairEtNet.Model.Affectation", b =>
                {
                    b.HasOne("ClairEtNet.Model.Chantier", "Chantier")
                        .WithMany("Affectations")
                        .HasForeignKey("Id_chantier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClairEtNet.Model.Employer", "Employer")
                        .WithMany("Affectations")
                        .HasForeignKey("Id_employer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chantier");

                    b.Navigation("Employer");
                });

            modelBuilder.Entity("ClairEtNet.Model.Employer", b =>
                {
                    b.HasOne("ClairEtNet.Model.Utilisateur", "Utilisateur")
                        .WithOne("Employer")
                        .HasForeignKey("ClairEtNet.Model.Employer", "Id_utilisateur")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("ClairEtNet.Model.Incident", b =>
                {
                    b.HasOne("ClairEtNet.Model.Chantier", "Chantier")
                        .WithMany("Incidents")
                        .HasForeignKey("Id_chantier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClairEtNet.Model.Employer", "Employer")
                        .WithMany("Incidents")
                        .HasForeignKey("Id_employer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chantier");

                    b.Navigation("Employer");
                });

            modelBuilder.Entity("ClairEtNet.Model.MouvementStock", b =>
                {
                    b.HasOne("ClairEtNet.Model.Chantier", "Chantier")
                        .WithMany("MouvementsStock")
                        .HasForeignKey("Id_chantier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClairEtNet.Model.Stock", "Stock")
                        .WithMany("MouvementsStock")
                        .HasForeignKey("Id_stock")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClairEtNet.Model.Utilisateur", "Utilisateur")
                        .WithMany("MouvementsStock")
                        .HasForeignKey("Id_utilisateur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chantier");

                    b.Navigation("Stock");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("ClairEtNet.Model.Stock", b =>
                {
                    b.HasOne("ClairEtNet.Model.Categorie", "Categorie")
                        .WithMany("Stocks")
                        .HasForeignKey("Id_categorie")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categorie");
                });

            modelBuilder.Entity("ClairEtNet.Model.Categorie", b =>
                {
                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("ClairEtNet.Model.Chantier", b =>
                {
                    b.Navigation("Affectations");

                    b.Navigation("Incidents");

                    b.Navigation("MouvementsStock");
                });

            modelBuilder.Entity("ClairEtNet.Model.Employer", b =>
                {
                    b.Navigation("Affectations");

                    b.Navigation("Incidents");
                });

            modelBuilder.Entity("ClairEtNet.Model.Stock", b =>
                {
                    b.Navigation("MouvementsStock");
                });

            modelBuilder.Entity("ClairEtNet.Model.Utilisateur", b =>
                {
                    b.Navigation("Employer");

                    b.Navigation("MouvementsStock");
                });
#pragma warning restore 612, 618
        }
    }
}
